//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSEMS.Models
{
    using Dapper;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PEE_Form
    {
        public int ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string item_description { get; set; }
        public string brand { get; set; }
        public string registration_no { get; set; }
        public Nullable<int> spec1 { get; set; }
        public Nullable<int> spec2 { get; set; }
        public Nullable<int> spec3 { get; set; }
        public Nullable<int> spec4 { get; set; }
        public Nullable<int> spec5 { get; set; }
        public Nullable<int> others { get; set; }
        public string action { get; set; }
        public Nullable<int> approved { get; set; }
        public Nullable<int> approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }

        public List<PEE_Form> details { get; set; }


        //public static PEE_Form GetAllForms(int ID, PEE_Form getforms)
        //{
        //    HSEMSEntities conn = new HSEMSEntities();
        //    var connection = conn.Database.Connection;

        //   var getdetails = connection.Query<PEE_Form>("SELECT * FROM PEE_Form  WHERE form_id = @formid",new { formid = ID }).ToList();

        //    foreach(var item in getdetails)
        //    {
        //        item.details = connection.Query<PEE_Form>("SELECT * FROM PEE_Form  WHERE ID = @formid", new { formid = item.ID }).FirstOrDefault();
        //    }

        //    return getforms;

        //}
    }
}
